language: python

python:
  - "2.6"
  - "2.7"
  - "3.5"
  - "3.6"
env:
  - UNPINNED="true"
  - PINNED=true

matrix:
  allow_failures:
    - env: UNPINNED="true"

install:
  - pip install -q coveralls --use-wheel

script:
  - python setup.py test
  - if [ "${TRAVIS_PYTHON_VERSION}" != "2.6" ]; then
      bandit -r puppetboard
      bandit -r test
    fi
after_success:
  - coveralls
