name: publish 🐳 Docker image

on: push
#on:
#  push:
#    tags:
#      - "v*"

env:
  TEST_TAG: voxpupuli/puppetboard:test

jobs:

  build-and-push-image:

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get tags
        shell: python
        run: |
          import re
          from packaging.version import parse

          version = "${{ github.ref }}".replace("refs/tags/v", "")
          image = "ghcr.io/${{ github.repository }}"

          tags = set()

          # full version
          tags.add(f"{image}:{version}")

          tags = ",".join(sorted(list(tags)))

          print(f"::set-output name=tags::{tags}")

        id: tags

      - name: Build the image with test tag
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64
          load: true
          tags: ${{ env.TEST_TAG }}

      - name: Test the image
        run: |
          docker run --rm ${{ env.TEST_TAG }}

#      - name: Build image with final tags and push
#        uses: docker/build-push-action@v3
#        with:
#          context: .
#          platforms: linux/amd64
#          push: true
#          tags: ${{ steps.tags.outputs.tags }}
