name: publish 🐍 egg to PyPI

on:
  push:
    tags:
      - "v*"

jobs:
  build-n-publish:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          pip install wheel
      - name: Build
        run: |
          python setup.py build sdist bdist_wheel
      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@v1.8.7
        with:
          password: ${{ secrets.PYPI_API_TOKEN_PUPPETBOARD }}
          # repository_url: https://test.pypi.org/legacy/
      - name: Create release in GitHub
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: false
          prerelease: false
