name: tests (unit)

# trigger on pushes to master OR PRs to master
# to prevent double tests on PRs within this repo
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      max-parallel: 5
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9, '3.10']

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install --upgrade wheel setuptools
          pip install -r requirements-test.txt
          mypy --install-types --non-interactive puppetboard/ test/
      - name: Test
        run: |
          pytest --cov=. --cov-report=xml --flake8 --strict-markers --mypy -v puppetboard test
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: true

  security-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          pip install bandit
      - name: Run bandit
        run: |
          bandit -r puppetboard
